S2B-Fase3/Mobius/Models/Relatorio.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace Mobius.Models
{
    public class Relatorio
    {
        [Key]
        public int ID { get; set; }

        public string Controller { get; set; }

        public string User { get; set; }

        public string Action { get; set; }

        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:u}")]
        public DateTime LogDate { get; set; }
    }
}

S2B-Fase3/Mobius/Controllers/CommentController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Mobius.Models;
using System.Data.Entity.Infrastructure;

namespace Mobius.Controllers
{
    public class CommentController : Controller
    {
        private ProductDbContext db = new ProductDbContext();

        // GET: Comment
        public ActionResult Index()
        {
            return View(db.Comments.Where(c => (c.UserEmail == User.Identity.Name) || (c.AnnouncerEmail == User.Identity.Name)).ToList());
        }

        // GET: Comment/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Comment comment = db.Comments.Find(id);
            if (comment == null)
            {
                return HttpNotFound();
            }
            return View(comment);
        }

        // GET: Comment/Create
        [Authorize]
        public ActionResult Create(int id, string productName, string announcerEmail)
        {
            ViewBag.ProductName = productName;
            ViewBag.ProductID = id;
            ViewBag.AnnoucerEmail = announcerEmail;
            return View();
        }

        // POST: Comment/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ID,ProductID,CommentDate,Comentario,Resposta,UserEmail")] Comment comment, int id, string announcerEmail)
        {
            if (ModelState.IsValid)
            {
                comment.ProductID = id;
                comment.UserEmail = User.Identity.Name;
                comment.AnnouncerEmail = announcerEmail;
                comment.CommentDate = DateTime.Now;
                db.Comments.Add(comment);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(comment);
        }

        // TODO Fix comments 
        // https://stackoverflow.com/questions/23201907/asp-net-mvc-attaching-an-entity-of-type-modelname-failed-because-another-ent
        // GET: Comment/Edit/5
        [Authorize]
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Comment comment = db.Comments.Find(id);
            if (comment == null)
            {
                return HttpNotFound();
            }
            return View(comment);
        }

        // POST: Comment/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult EditResposta(Comment comment)
        {
            if (ModelState.IsValid)
            {
                bool saveFailed;
                do
                {
                    saveFailed = false;

                    try
                    {
                        db.Entry(comment).State = EntityState.Modified;
                        db.SaveChanges();
                        return RedirectToAction("Index");
                    }
                    catch (DbUpdateConcurrencyException ex)
                    {
                        saveFailed = true;

                        // Update original values from the database 
                        var entry = ex.Entries.Single();
                        entry.OriginalValues.SetValues(entry.GetDatabaseValues());
                    }

                } while (saveFailed);
            }
            return View(comment);
        }

        // POST: Comment/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult EditComentario(Comment comment)
        {
            if (ModelState.IsValid)
            {
                bool saveFailed;
                do
                {
                    saveFailed = false;

                    try
                    {
                        db.Entry(comment).State = EntityState.Modified;
                        db.SaveChanges();
                        return RedirectToAction("Index");
                    }
                    catch (DbUpdateConcurrencyException ex)
                    {
                        saveFailed = true;

                        // Update original values from the database 
                        var entry = ex.Entries.Single();
                        entry.OriginalValues.SetValues(entry.GetDatabaseValues());
                    }

                } while (saveFailed);
            }
            return View(comment);
        }

        // GET: Comment/Delete/5
        [Authorize]
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Comment comment = db.Comments.Find(id);
            if (comment == null)
            {
                return HttpNotFound();
            }
            if (comment.UserEmail == User.Identity.Name)
            {
                return View(comment);
            }
            return new HttpStatusCodeResult(HttpStatusCode.Unauthorized);
        }

        // POST: Comment/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Comment comment = db.Comments.Find(id);
            db.Comments.Remove(comment);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

S2B-Fase3/Mobius/Controllers/ProductController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Mobius.Models;
using System.Security.Principal;

namespace Mobius.Controllers
{
    public class ProductController : Controller
    {
        private ProductDbContext db = new ProductDbContext();

        protected override void OnActionExecuting(ActionExecutingContext filterContext)
        {
            string user = filterContext.HttpContext.User.Identity.Name;
            if(user == null || user == "")
            {
                user = "Visitante";
            }
            //Para não encher o log com "GetImage" & "Relatorios"
            string action = filterContext.ActionDescriptor.ActionName;
            if(!action.Equals("GetImage") && !action.Equals("Relatorios"))
            {
                db.Relatorios.Add(
                    new Relatorio
                    {
                        Controller = filterContext.ActionDescriptor.ControllerDescriptor.ControllerName,
                        User = user,
                        Action = action,
                        LogDate = DateTime.Now
                    });
                db.SaveChanges();
            }
        }

        //If action filter does not work...
        private void PlusRating(IPrincipal user)
        {
            var u = user as MyProfile;
            u.Rating += 1;
            //Update user in DB
        }

        [Authorize(Users = "admin@s2b.br")]
        public ActionResult Relatorios()
        {
            return View(db.Relatorios.OrderBy(r => r.LogDate).ToList());
        }

        //Return image file
        public ActionResult GetImage(int id)
        {
            Product product = db.Products.Find(id);
            if(product != null && product.ImageFile != null)
            {
                //File used to return a binary content and the contenttype of the returned photo
                return File(product.ImageFile, product.ImageMimeType);
            }
            else
            {
                //Should return a default "Image not found" image
                return new FilePathResult("~/Images/nao-disponivel.jpg", "image/jpeg");
            }
        }

        [Authorize(Users = "admin@s2b.br")]
        public ActionResult CheckExpirationDate()
        {
            var products = db.Products.ToList();
            products.ForEach(p =>
            {
                if(DateTime.Compare(p.ExpirationDate, DateTime.Now) < 0)
                {
                    p.Status = Status.Expired;
                    db.Entry(p).State = EntityState.Modified;
                    db.SaveChanges();
                }
            });

            return RedirectToAction("Index", "Manage", null);
        }

        // GET: Product
        //Browse Method...List all products... TODO Create Filters
        public ActionResult Index()
        {
            return View(db.Products.Where(p => p.Status == Status.Open).ToList());
        }

        // Show User's Products
        [Authorize]
        public ActionResult Browse()
        {
            return View(db.Products.Where(p => p.UserEmail == User.Identity.Name).ToList());
        }

        //Show User's negotiations
        [Authorize]
        public ActionResult Negotiations()
        {
            return View(db.Products.Where(
                    p => (p.BuyerEmail == User.Identity.Name) &&
                    ((p.Status == Status.Negotiating) || (p.Status == Status.Sold))
                ).ToList());
        }

        // GET: Product/Details/5
        // Show Product details to product owner...
        [Authorize]
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Product product = db.Products.Find(id);
            if (product == null)
            {
                return HttpNotFound();
            }

            if(User.Identity.Name != product.UserEmail)
            {
                return new HttpStatusCodeResult(HttpStatusCode.Unauthorized);
            }
            return View(product);
        }

        // GET: Product/Create
        [Authorize]
        public ActionResult Create()
        {
            ViewBag.CategoryID = new SelectList(db.Categories, "CategoryID", "Name");
            return View();
        }

        // POST: Product/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ProductID,Title,Description,Cost,Address,PublishDate,ExpirationDate,Status,Rating,ImageFile,ImageMimeType,ImageUrl,CategoryID,UserEmail")]
                                    Product product, HttpPostedFileBase image)
        {
            if (ModelState.IsValid)
            {
                //if image object is not empty update the photo attribute, using image info.
                if (image != null)
                {
                    product.ImageMimeType = image.ContentType;
                    product.ImageFile = new byte[image.ContentLength];
                    //save the photo file by using image.InputStream.Read method.
                    image.InputStream.Read(product.ImageFile, 0, image.ContentLength);
                }
                product.PublishDate = DateTime.Now;
                product.ExpirationDate = DateTime.Now.AddDays(60);
                product.Status = Status.Open;
                product.Rating = 0;
                product.UserEmail = User.Identity.Name;
                db.Products.Add(product);
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.CategoryID = new SelectList(db.Categories, "CategoryID", "Name", product.CategoryID);
            return View(product);
        }

        // GET: Product/Edit/5
        [Authorize]
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Product product = db.Products.Find(id);
            if (product == null)
            {
                return HttpNotFound();
            }
            ViewBag.CategoryID = new SelectList(db.Categories, "CategoryID", "Name");
            return View(product);
        }

        // POST: Product/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(/*[Bind(Include = "ProductID,Title,Description,Cost,Address,Status,Rating,ImageFile,ImageMimeType,ImageUrl,CategoryID,UserEmail",
                                    Exclude = "PublishDate,ExpirationDate")]*/
                                    Product product, HttpPostedFileBase image)
        {
            /*
             https://forums.asp.net/t/1999919.aspx?MVC+readonly+datetime+updates+to+01+01+0001
             Dates wheren't behaving properly...
             fetching product so Publish/Expiration dates won't be set as '1/1/0001' and create an exception...
             */
            var fetchedProduct = db.Products.Find(product.ProductID);
            fetchedProduct.Address = product.Address;
            fetchedProduct.CategoryID = product.CategoryID;
            fetchedProduct.Title = product.Title;
            fetchedProduct.Description = product.Description;
            fetchedProduct.Cost = product.Cost;
            if (ModelState.IsValid)
            {
                //if image object is not empty update the photo attribute, using image info.
                if (image != null)
                {
                    fetchedProduct.ImageMimeType = image.ContentType;
                    fetchedProduct.ImageFile = new byte[image.ContentLength];
                    //save the photo file by using image.InputStream.Read method.
                    image.InputStream.Read(fetchedProduct.ImageFile, 0, image.ContentLength);
                }
                var teste = fetchedProduct.PublishDate;
                var teste2 = fetchedProduct.ExpirationDate;
                db.Entry(fetchedProduct).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.CategoryID = new SelectList(db.Categories, "CategoryID", "Name", product.CategoryID);
            return View(product);
        }

        // GET: Product/Cancel/5
        // Delete Changed to -> Cancel
        [Authorize]
        public ActionResult Cancel(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Product product = db.Products.Find(id);
            if (product == null)
            {
                return HttpNotFound();
            }
            return View(product);
        }

        // POST: Product/Cancel/5
        [HttpPost, ActionName("Cancel")]
        [ValidateAntiForgeryToken]
        public ActionResult CancelConfirmed(int id)
        {
            Product product = db.Products.Find(id);
            if(product != null)
            {
                product.Status = Status.Cancelled;
                db.Entry(product).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Browse");
            }
            return View(product);
        }

        // GET: Product/Donate/5
        [Authorize]
        public ActionResult Donate(int? id)
        {
            if(id == null)
            {

S2B-Fase3/Mobius/Views/Product/Browse.cshtml
@model IEnumerable<Mobius.Models.Product>

@{
    ViewBag.Title = "Visualizar seus Produtos";
}

<h2>@ViewBag.Title</h2>

<p>
    @Html.ActionLink("Novo Produto", "Create", null, new { @class = "btn btn-success" })
</p>

@if (Model.Count() < 1)
{
    <strong>Você não possui nenhum produto cadastrado!</strong>
}
else
{
    foreach (var item in Model)
    {
        @Html.Partial("_ProductFragment", item)
    }
}

S2B-Fase3/Mobius/Views/Product/Cancel.cshtml
@model Mobius.Models.Product

@{
    ViewBag.Title = "Cancel";
}

<h2>Cancel</h2>

<h3>Are you sure you want to ~Cancelar~ this?</h3>
<div>
    <h4>Product</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Title)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Title)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Description)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Description)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Cost)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Cost)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Address)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Address)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PublishDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PublishDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ExpirationDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ExpirationDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Status)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Status)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Rating)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Rating)
        </dd>
        @* TODO Change to image tag *@
        @*<dt>
            @Html.DisplayNameFor(model => model.ImageFile)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ImageFile)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ImageMimeType)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ImageMimeType)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ImageUrl)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ImageUrl)
        </dd>*@

        <dt>
            @Html.DisplayNameFor(model => model.CategoryID)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CategoryID)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.UserEmail)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.UserEmail)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Cancelar" class="btn btn-danger" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

S2B-Fase3/Mobius/Views/Product/Create.cshtml
@model Mobius.Models.Product

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm("Create", "Product", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Product</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Title, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Title, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Title, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Cost, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Cost, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Cost, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Address, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Address, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Address, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ImageFile, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <label class="btn btn-default btn-file" for="Image">
                    Enviar Arquivo
                    <input type="file" name="Image" style="display: none" />
                </label>
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ImageUrl, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ImageUrl, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ImageUrl, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CategoryID, "CategoryID", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("CategoryID", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.CategoryID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Voltar", "Index", "Manage")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

S2B-Fase3/Mobius/Views/Product/Edit.cshtml
@model Mobius.Models.Product

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm("Edit", "Product", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Product</h4>
        <p>For Testing purposes...</p>
        <p>@Model.PublishDate</p>
        <p>@Model.ExpirationDate</p>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.ProductID)

        <div class="form-group">
            @Html.LabelFor(model => model.Title, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Title, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Title, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Cost, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Cost, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Cost, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Address, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Address, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Address, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ImageFile, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <label class="btn btn-default btn-file" for="Image">
                    Enviar Arquivo
                    <input type="file" name="Image" style="display: none" />
                </label>
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ImageUrl, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ImageUrl, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ImageUrl, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CategoryID, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("CategoryID", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.CategoryID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

S2B-Fase3/Mobius/Views/Product/_ProductFragment.cshtml
@model Mobius.Models.Product

@* TODO Review this partial view *@

<div class="panel panel-primary">

    <div class="panel-body">
        <h5>@Model.Title</h5>
        <h6>TesteID: @Model.ProductID</h6>

        <p>@Model.Status</p>

        <img width="200" src="@Url.Action("GetImage", "Product", new { id = Model.ProductID })" alt="@Model.Title , Imagem" />
        @if (Model.ImageUrl != null)
        {
            <img width="200" src="@Model.ImageUrl" alt="@Model.Title , Imagem" />
        }

        <p>@Model.Description</p>

        <p>@Model.Cost</p>

        <p>@Model.Address</p>

        <p>@Model.PublishDate.ToString(string.Format("dd/MM/yyyy"))</p>

        <p>@Model.ExpirationDate.ToString(string.Format("dd/MM/yyyy"))</p>
    </div>

    <div class="panel-footer">
        <p>Por: @Model.UserEmail</p>
        <p>Categoria: @Model.Category.Name</p>

        @if (User.Identity.Name == Model.UserEmail)
        {
            <div class="btn-group btn-group-sm btn-group-justified">
                @if (Model.Status == Mobius.Models.Status.Open)
                {
                    @Html.ActionLink("Cancelar Anúncio", "Cancel", new { id = Model.ProductID }, new { @class = "btn btn-danger btn-sm" })
                    @Html.ActionLink("Editar Anúncio", "Edit", new { id = Model.ProductID }, new { @class = "btn btn-primary btn-sm" })
                }
                else if (Model.Status == Mobius.Models.Status.Expired)
                {
                    @Html.ActionLink("Doar Produto", "Donate", new { id = Model.ProductID }, new { @class = "btn btn-info btn-sm" })
                    @Html.ActionLink("Cancelar Anúncio", "Cancel", new { id = Model.ProductID }, new { @class = "btn btn-danger btn-sm" })
                }
                else if (Model.Status == Mobius.Models.Status.Negotiating)
                {
                    @Html.ActionLink("Confirmar Venda", "SellTo", new { id = Model.ProductID }, new { @class = "btn btn-success btn-sm" })
                    @Html.ActionLink("Cancelar Anúncio", "Cancel", new { id = Model.ProductID }, new { @class = "btn btn-danger btn-sm" })
                }

                @Html.ActionLink("Perguntas", "Index", "Comment", new { @class = "btn btn-info btn-sm" })
            </div>
            //CONTACT -> View Messages...
            <p>I CREATED THIS</p>
        }
        else if (User.Identity.Name == Model.BuyerEmail)
        {
            if (Model.Status == Mobius.Models.Status.Sold && Model.Rated == true)
            {
                <strong>Voce avaliou este produto com @Model.Rating pontos</strong>
            }
            <div class="btn-group btn-group-sm btn-group-justified">
                @if (Model.Status == Mobius.Models.Status.Sold && Model.Rated == false)
                {
                    @Html.ActionLink("Avaliar", "Rate", "Product", new { id = Model.ProductID }, new { @class = "btn btn-success btn-sm" });
                }
                @Html.ActionLink("Contatar o Vendedor", "Create", "Comment", new { id = Model.ProductID, productName = Model.Title, announcerEmail = Model.UserEmail }, new { @class = "btn btn-info btn-sm" })
            </div>
            <p>I AM NEGOTIATING THIS / I BOUGHT THIS</p>
        }
        else
        {
            //Not the creator
            //CONTACT -> Create Messages...
            <div class="btn-group btn-group-sm btn-group-justified">
                @Html.ActionLink("Comprar", "Negotiate", new { id = Model.ProductID }, new { @class = "btn btn-success btn-sm" })
                @Html.ActionLink("Contatar o Vendedor", "Create", "Comment", new { id = Model.ProductID, productName = Model.Title }, new { @class = "btn btn-info btn-sm" })
            </div>
            <p>I MAY BUY THIS</p>
        }


        @if(User.Identity.Name == "admin@s2b.br")
        {
            <div class="btn-group btn-group-sm btn-group-justified">
            </div>
            <p>I MAY ADMINISTRATE THIS</p>
        }
    </div>
</div>